{
 "title": "Datastores",
 "description": "OmegaGraf dashboard providing insight into Datastores inside vCenter.",
 "tags": [
  "vsphere",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "vcenter", "label": "vCenter", "query": "label_values(vcenter)" }
  ]
 },
 "panels": [
  { "title": "$vcenter Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "vcenter" },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(vsphere_datastore_disk_capacity_latest{vcenter=\"$vcenter\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(vsphere_datastore_disk_provisioned_latest{vcenter=\"$vcenter\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(vsphere_datastore_disk_used_latest{vcenter=\"$vcenter\"})"
    }
   ]
  },
  {
   "title": "Datastore Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "clamp_max(vsphere_datastore_disk_used_latest{vcenter=\"$vcenter\"} / vsphere_datastore_disk_capacity_latest{vcenter=\"$vcenter\"}, 1)",
     "legendFormat": "{{ dsname }}"
    }
   ]
  },
  { "title": "$vcenter Datastore Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "vcenter" },
  {
   "title": "Datastore Used Capacity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "clamp_max(vsphere_datastore_disk_used_latest{vcenter=\"$vcenter\"} / vsphere_datastore_disk_capacity_latest{vcenter=\"$vcenter\"}, 1)",
     "legendFormat": "{{ dsname }}"
    },
    {
     "expr": "clamp_min(clamp_max((predict_linear(vsphere_datastore_disk_used_latest{vcenter=\"$vcenter\"}[1h], 4 * 3600) / vsphere_datastore_disk_capacity_latest{vcenter=\"$vcenter\"}), 1), 0)",
     "legendFormat": "{{ dsname }} - Prediction"
    }
   ]
  },
  {
   "title": "Datastore Provisioning",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "vsphere_datastore_disk_provisioned_latest{vcenter=\"$vcenter\"} / vsphere_datastore_disk_capacity_latest{vcenter=\"$vcenter\"}",
     "legendFormat": "{{ dsname }}"
    },
    {
     "expr": "clamp_min((predict_linear(vsphere_datastore_disk_provisioned_latest{vcenter=\"$vcenter\"}[1h], 4 * 3600) / vsphere_datastore_disk_capacity_latest{vcenter=\"$vcenter\"}), 0)",
     "legendFormat": "{{ dsname }} - Prediction"
    }
   ]
  },
  {
   "title": "Datastore Reads/Writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "vsphere_datastore_datastore_write_average{vcenter=\"$vcenter\"}",
     "legendFormat": "{{ source }} - Write"
    },
    {
     "expr": "vsphere_datastore_datastore_read_average{vcenter=\"$vcenter\"}",
     "legendFormat": "{{ source }} - Read"
    }
   ]
  }
 ]
}