{
 "title": "Telegraf",
 "tags": [
  "telegraf",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "internal_vsphere_connect_ns", "legendFormat": "{{ vcenter }} Connect" },
    { "expr": "internal_vsphere_discover_ns", "legendFormat": "{{ vcenter }} Discover" }
   ]
  },
  {
   "title": "vSphere Discovered Objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "internal_vsphere_discovered_objects{type!=\"instance-total\"}",
     "legendFormat": "{{ type }} {{ vcenter }}"
    }
   ]
  },
  {
   "title": "vSphere Gathered Objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "internal_vsphere_gather_count{resourcetype!=\"instance-total\"}",
     "legendFormat": "{{ resourcetype}} {{ vcenter }}"
    }
   ]
  },
  {
   "title": "vSphere Gather Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "internal_vsphere_gather_duration_ns{resourcetype!=\"instance-total\"}",
     "legendFormat": "{{ resourcetype}} {{ vcenter }}"
    }
   ]
  }
 ]
}