{
 "title": "Virtual Machines",
 "description": "OmegaGraf dashboard of tables providing the latest VM measures from vCenter.",
 "tags": [
  "monitoring",
  "vsphere"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "VM CPU Stats",
   "type": "table",
   "gridPos": { "h": 33, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(vsphere_vm_cpu_usage_average) by (vcenter, vmname)"
    },
    {
     "expr": "sum(vsphere_vm_cpu_usagemhz_average) by (vcenter, vmname)"
    },
    {
     "expr": "sum(vsphere_vm_cpu_readiness_average) by (vcenter, vmname)"
    }
   ]
  },
  {
   "title": "VM Memory Stats",
   "type": "table",
   "gridPos": { "h": 33, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(vsphere_vm_mem_active_average) by (vcenter, vmname)"
    },
    {
     "expr": "sum(vsphere_vm_mem_usage_average) by (vcenter, vmname)"
    },
    {
     "expr": "sum(vsphere_vm_mem_consumed_average) by (vcenter, vmname)"
    }
   ]
  },
  {
   "title": "VM Network Stats",
   "type": "table",
   "gridPos": { "h": 33, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(vsphere_vm_net_usage_average) by (vcenter, vmname)"
    },
    {
     "expr": "sum(vsphere_vm_net_bytesRx_average) by (vcenter, vmname)"
    },
    {
     "expr": "sum(vsphere_vm_net_bytesTx_average) by (vcenter, vmname)"
    }
   ]
  }
 ]
}